Create Procedure FIRMAHAREKETLERI
As
Select HAREKETID,URUNAD,TBL_FIRMAHAREKETLER.ADET,
(TBL_PERSONELLER.AD +' '+SOYAD) AS PERSONEL,
(TBL_FIRMALAR.AD) AS FIRMA,FIYAT,TOPLAM,FATURAID 
From TBL_FIRMAHAREKETLER 
inner join TBL_URUNLER on 
TBL_URUNLER.ID=TBL_FIRMAHAREKETLER.URUNID 
inner join TBL_PERSONELLER on
 TBL_PERSONELLER.ID = TBL_FIRMAHAREKETLER.PERSONEL
inner join TBL_FIRMALAR on
 TBL_FIRMALAR.ID= TBL_FIRMAHAREKETLER.FIRMA
